name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Setup venv
        run: |
          python3 -m venv venv
          pip3 install --upgrade pip setuptools wheel
          pip3 install -e .[dev]
          source ./venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 python \
            --show-source \
            --statistics \
            --ignore=E203,E501 \
            --max-line-length=127 \
            --max-complexity=10
      - name: Install
        run: |
          sudo ./setup.py install
      - name: Test
        run: |
          sudo ./setup.py install
          python3 -m pytest -q -s \
            --data-paths ./tests/data/calibration/left \
                         ./tests/data/calibration/right \
            --rms-threshold 1.5 \
            -- tests/test_calibration.py
