name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Setup venv
        run: |
          python3 -m venv venv
          pip3 install --upgrade pip setuptools wheel
          source ./venv/bin/activate
      - name: Install dependencies
        run: |
          git submodule update --init --recursive
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          sudo apt-get update
          sudo apt-get install \
            build-essential cmake make libopencv-dev python3-opencv \
            libeigen3-dev pybind11-dev flake8 libfmt-dev
      - name: Lint
        run: |
          flake8 src \
            --show-source \
            --statistics \
            --ignore=E203,E501 \
            --max-line-length=127 \
            --max-complexity=10
      - name: Build
        run: |
          cmake -S third_party/Sophus -B sophus-build -DBUILD_SOPHUS_EXAMPLES=OFF -DBUILD_SOPHUS_TESTS=OFF
          sudo cmake --build sophus-build --target install -j18
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          sudo cmake --build build --target install -j18
          pip3 install -e .
      - name: Test
        run: |
          python3 -m pytest -q -s src/tests
