name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Ubuntu_2004_Build_Test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "true"
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install system dependencies
        run: |
          sudo ./tools/install_dependencies_ubuntu.sh
      - name: Setup Python virtual environment
        run: |
          python3 -m venv venv
          pip3 install --upgrade pip setuptools wheel
          source ./venv/bin/activate
      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
      - name: Lint Python files
        run: |
          flake8 src \
            --show-source \
            --statistics \
            --max-line-length=127 \
            --max-complexity=10
      - name: Build C++ libraries
        run: |
          cmake -S . -B /tmp/mvgkit_build -DCMAKE_BUILD_TYPE=ASAN -DBUILD_MVGKIT_TESTS=ON
          sudo cmake --build /tmp/mvgkit_build --target install -j16
      - name: Install Python packages
        run: |
          python setup.py build -j 16 install
      - name: Test Python packages
        run: |
          ./tools/run_test.py --build-dir /tmp/mvgkit_build -p -1
